export interface ProductData {
    name: string;
    title: string;
    brand: string;
    imageUrls: string[];
    originalPrice: string;
    discountedPrice: string;
    category: string;
    subcategory: string;
    quantity: string;
    size: string;
    description: string;
    material: string;
    weight: string;
    dimensions: string;
    manufacturingDate: string;
    warranty: string;
    shippingInfo: string;
    highlights: string[];
    stockAlert: string;
  }
  

  export const subcategorySizeMap: { [key: string]: string } = {
    "gloves": "clothing",
    "reflectiveVests": "clothing",
    "resistantJackets": "clothing",
    "yogaPants": "clothing",
    "yogaTops": "clothing",
    "yogaShorts": "clothing",
    "yogaBra": "clothing",
    "cricketClothing": "clothing",
    "cricketShoes": "shoes",
    "battingPads": "clothing",
    "battingGloves": "clothing",
    "protectiveHelmet": "clothing",
    "tennisTops": "clothing",
    "tennisShorts": "clothing",
    "courtShoes": "shoes",
    "swimsuits": "clothing",
    "swimShorts": "clothing",
    "headCaps": "clothing",
    "cyclingJerseys": "clothing",
    "cyclingShorts": "clothing",
    "cyclingShoes": "shoes",
    "cyclingHelmet": "clothing",
    "sportUniform": "clothing",
    "winterBoots": "shoes",
    "jackets": "clothing",
    "pants": "clothing",
    "thermalWear": "clothing",
    "kidsClothing": "clothing",
    "kidsShoes": "shoes",
    "sportsSocks": "clothing",
    "sportsCaps": "clothing",
    "hoodies": "clothing",
    "t-shirts": "clothing",
    "jeans": "clothing",
    "shorts": "clothing",
    "sneakers": "shoes",
    "boots": "shoes",
    "sandals": "shoes",
    "flipFlops": "shoes",
    "dressShoes": "shoes",
    "formalWear": "clothing",
    "activewear": "clothing",
    "outerwear": "clothing",
    "accessories": "clothing",
    "sportsBras": "clothing",
    "workoutLeggings": "clothing",
    "compressionShirts": "clothing",
    "runningTights": "clothing",
    "swimwear": "clothing",
    "trackPants": "clothing",
    "cargoPants": "clothing",
    "slippers": "shoes",
    "clogs": "shoes",
    "ankleBoots": "shoes",
    "highHeels": "shoes",
  };


  export const sizeOptionsMap: { [key: string]: string[] } = {
    clothing: ["XS", "S", "M", "L", "XL", "XXL", "3XL"],
    shoes: ["UK6_EU39", "UK7_EU40", "UK8_EU41", "UK9_EU42", "UK10_EU43", "UK11_EU44", "UK12_EU45"],
  };

export const categories = [
  {
    category: "Pet Care",
    label: "Pet Care",
    subcategories: [
      { value: "dogFood", label: "Dog Food" },
      { value: "catFood", label: "Cat Food" },
      { value: "birdFood", label: "Bird Food" },
      { value: "fishFood", label: "Fish Food" },
      { value: "smallAnimalFood", label: "Small Animal Food" },
      { value: "petToys", label: "Pet Toys" },
      { value: "petBeds", label: "Pet Beds" },
      { value: "petGrooming", label: "Pet Grooming Supplies" },
      { value: "petHealthCare", label: "Pet Health Care" },
      { value: "petTraining", label: "Pet Training Supplies" },
      { value: "petClothing", label: "Pet Clothing" },
      { value: "petAccessories", label: "Pet Accessories" },
      { value: "aquariumSupplies", label: "Aquarium Supplies" },
      { value: "reptileSupplies", label: "Reptile Supplies" },
      { value: "petTravel", label: "Pet Travel Accessories" },
      { value: "petCleaning", label: "Pet Cleaning Supplies" },
      { value: "petCarriers", label: "Pet Carriers" },
      { value: "petLeashes", label: "Pet Leashes" },
      { value: "petCollars", label: "Pet Collars" },
      { value: "petMats", label: "Pet Mats" },
      { value: "petBowls", label: "Pet Bowls and Feeders" },
      { value: "petWaterFountains", label: "Pet Water Fountains" },
      { value: "petLitter", label: "Pet Litter" },
      { value: "petLitterBoxes", label: "Pet Litter Boxes" },
      { value: "petFleaAndTickControl", label: "Flea and Tick Control" },
      { value: "petHealthSupplements", label: "Pet Health Supplements" },
      { value: "petDentalCare", label: "Pet Dental Care" },
      { value: "petEyeCare", label: "Pet Eye Care" },
      { value: "petEarCare", label: "Pet Ear Care" },
      { value: "petNailCare", label: "Pet Nail Care" },
      { value: "petShampoos", label: "Pet Shampoos and Conditioners" },
      { value: "petSunscreen", label: "Pet Sunscreen" },
      { value: "petCoolingProducts", label: "Pet Cooling Products" },
      { value: "petCages", label: "Pet Cages" },
      { value: "petPlaypens", label: "Pet Playpens" },
      { value: "petSnacks", label: "Pet Snacks and Treats" },
      { value: "petChews", label: "Pet Chews" },
      { value: "petHealthMonitors", label: "Pet Health Monitors" },
      { value: "petDiapers", label: "Pet Diapers" },
      { value: "petEarAndEyeWipes", label: "Pet Ear and Eye Wipes" },
      { value: "petBrushes", label: "Pet Brushes and Combs" },
      { value: "petFurRemovers", label: "Pet Fur Removers" },
      { value: "petTreadmills", label: "Pet Treadmills" },
      { value: "petVitamins", label: "Pet Vitamins" },
      { value: "petJumpsuits", label: "Pet Jumpsuits" },
      { value: "petRaincoats", label: "Pet Raincoats" },
      { value: "petBoots", label: "Pet Boots" },
      { value: "petCoolingMats", label: "Pet Cooling Mats" },
      { value: "petHeatingPads", label: "Pet Heating Pads" },
      { value: "petPillows", label: "Pet Pillows" },
      { value: "petTents", label: "Pet Tents" },
      { value: "petRamps", label: "Pet Ramps" },
      { value: "petStairs", label: "Pet Stairs" },
      { value: "petSeatCovers", label: "Pet Seat Covers" },
      { value: "petHygieneProducts", label: "Pet Hygiene Products" }
    ]
  },  

  {
    category: "First Aid and Personal Care",
    label: "First Aid and Personal Care",
    subcategories: [
      { value: "skincare", label: "Skincare" },
      { value: "haircare", label: "Haircare" },
      { value: "oralcare", label: "Oral Care" },
      { value: "perfumesandDeodorants", label: "Perfumes and Deodorants" },
      { value: "shaving", label: "Shaving" },
      { value: "bathandbody", label: "Bath and Body" },
      { value: "healthcare", label: "Health Care" },
      { value: "feminineHygiene", label: "Feminine Hygiene" },
      { value: "babyCare", label: "Baby Care" },
      { value: "firstAidKits", label: "First Aid Kits" },
      { value: "bandages", label: "Bandages" },
      { value: "gauze", label: "Gauze" },
      { value: "tapes", label: "Tapes" },
      { value: "massagers", label: "Massagers" },
      { value: "disinfectants", label: "Disinfectants" },
      { value: "antiseptics", label: "Antiseptics" },
      { value: "painRelief", label: "Pain Relief" },
      { value: "burnCare", label: "Burn Care" },
      { value: "eyeCare", label: "Eye Care" },
      { value: "splints", label: "Splints" },
      { value: "coldPacks", label: "Cold Packs" },
      { value: "hotPacks", label: "Hot Packs" },
      { value: "firstAidBags", label: "First Aid Bags" },
      { value: "medicalTape", label: "Medical Tape" },
      { value: "woundCleaner", label: "Wound Cleaner" },
      { value: "antibioticOintments", label: "Antibiotic Ointments" },
      { value: "elasticBandages", label: "Elastic Bandages" },
      { value: "hemostaticDressings", label: "Hemostatic Dressings" },
      { value: "splintKits", label: "Splint Kits" },
      { value: "nasalSprays", label: "Nasal Sprays" },
      { value: "firstAidManuals", label: "First Aid Manuals" },
      { value: "instantColdPacks", label: "Instant Cold Packs" },
      { value: "instantHotPacks", label: "Instant Hot Packs" },
      { value: "sterilePads", label: "Sterile Pads" },
      { value: "surgicalMasks", label: "Surgical Masks" },
      { value: "toiletries", label: "Toiletries" },
      { value: "inhalers", label: "Inhalers" },
      { value: "vicksVaporRub", label: "Vicks Vapor Rub" },
      { value: "disposableGloves", label: "Disposable Gloves" },
      { value: "antisepticWipes", label: "Antiseptic Wipes" },
      { value: "cottonWool", label: "Cotton Wool" },
      { value: "nasalBalm", label: "Nasal Balm" },
      { value: "cottonSwabs", label: "Cotton Swabs" },
      { value: "thermometers", label: "Thermometers" },
      { value: "handSanitizers", label: "Hand Sanitizers" },
      { value: "disposableMasks", label: "Disposable Masks" },
      { value: "sanitaryPads", label: "Sanitary Pads" },
      { value: "eyeDrops", label: "Eye Drops" },
      { value: "glucoseGels", label: "Glucose Gels" },
      { value: "antifungalCreams", label: "Antifungal Creams" },
      { value: "lipBalms", label: "Lip Balms" },
      { value: "throatLozenges", label: "Throat Lozenges" },
      { value: "footCreams", label: "Foot Creams" },
      { value: "musclePainCreams", label: "Muscle Pain Creams" },
      { value: "coldSoreCreams", label: "Cold Sore Creams" },
      { value: "antiItchCreams", label: "Anti-Itch Creams" },
      { value: "healingOils", label: "Healing Oils" },
      { value: "poreStrips", label: "Pore Strips" },
      { value: "disposableRazor", label: "Disposable Razor" },
      { value: "medicatedShampoos", label: "Medicated Shampoos" },
      { value: "athletesFootCream", label: "Athlete's Foot Cream" },
      { value: "eyebrowTweezers", label: "Eyebrow Tweezers" },
      { value: "painReliefSprays", label: "Pain Relief Sprays" },
      { value: "stressReliefCreams", label: "Stress Relief Creams" },
      { value: "footSprays", label: "Foot Sprays" }
    ]
  },
  
  
    {
      category: "Gym Essentials",
      label: "Gym Essentials",
      subcategories: [
        { value: "dumbbells", label: "Dumbbells" },
        { value: "kettlebells", label: "Kettlebells" },
        { value: "resistanceBands", label: "Resistance Bands" },
        { value: "yogaMats", label: "Yoga Mats" },
        { value: "exerciseBalls", label: "Exercise Balls" },
        { value: "jumpRopes", label: "Jump Ropes" },
        { value: "foamRollers", label: "Foam Rollers" },
        { value: "barbells", label: "Barbells" },
        { value: "pullUpBars", label: "Pull-Up Bars" },
        { value: "gymGloves", label: "Gym Gloves" },
        { value: "gymBelts", label: "Gym Belts" },
        { value: "resistanceLoops", label: "Resistance Loops" },
        { value: "abWheels", label: "Ab Wheels" },
        { value: "medicineBalls", label: "Medicine Balls" },
        { value: "powerBlocks", label: "PowerBlocks" },
        { value: "agilityLadders", label: "Agility Ladders" },
        { value: "sleds", label: "Sleds" },
        { value: "battleRopes", label: "Battle Ropes" },
        { value: "ankleWeights", label: "Ankle Weights" },
        { value: "weightedVests", label: "Weighted Vests" },
        { value: "powerRacks", label: "Power Racks" },
        { value: "squatRacks", label: "Squat Racks" },
        { value: "resistanceTubes", label: "Resistance Tubes" },
        { value: "gymShorts", label: "Gym Shorts" },
        { value: "trainingTShirts", label: "Training T-Shirts" },
        { value: "compressionTights", label: "Compression Tights" },
        { value: "sportsBras", label: "Sports Bras" },
        { value: "workoutLeggings", label: "Workout Leggings" },
        { value: "runningShoes", label: "Running Shoes" },
        { value: "trainingShoes", label: "Training Shoes" },
        { value: "sweatbands", label: "Sweatbands" },
        { value: "workoutHats", label: "Workout Hats" },
        { value: "headbands", label: "Headbands" },
        { value: "liftingStraps", label: "Lifting Straps" },
        { value: "liftingChalk", label: "Lifting Chalk" },
        { value: "gymTowels", label: "Gym Towels" },
        { value: "gymBags", label: "Gym Bags" }
      ]
    },   

    {
      category: "Outdoor Equipment",
      label: "Outdoor Equipment",
      subcategories: [
        { value: "reflectiveVests", label: "Reflective Vests and Bands" },
        { value: "fannyPacks", label: "Fanny Packs" },
        { value: "runningBelts", label: "Running Belts" },
        { value: "sunglasses", label: "Sunglasses" },
        { value: "sunscreen", label: "Sunscreen" },
        { value: "perfumesandDeodorants", label: "Perfumes and Deodorants" },
        { value: "insectRepellents", label: "Insect Repellents" },
        { value: "outdoorTowels", label: "Outdoor Towels" },
        { value: "outdoorBlankets", label: "Outdoor Blankets" },
        { value: "coolers", label: "Coolers" },
        { value: "campingTents", label: "Camping Tents" },
        { value: "sleepingBags", label: "Sleeping Bags" },
        { value: "campingStoves", label: "Camping Stoves" },
        { value: "campingLanterns", label: "Camping Lanterns" },
        { value: "campingCookware", label: "Camping Cookware" },
        { value: "campingUtensils", label: "Camping Utensils" },
        { value: "campingKnives", label: "Camping Knives" },
        { value: "campingTools", label: "Camping Tools" },
        { value: "campingHammocks", label: "Camping Hammocks" },
        { value: "campingTarps", label: "Camping Tarps" },
        { value: "campingRopes", label: "Camping Ropes" },
        { value: "campingPoles", label: "Camping Poles" },
        { value: "campingStakes", label: "Camping Stakes" },
        { value: "campingMallets", label: "Camping Mallets" },
        { value: "campingRepairKits", label: "Camping Repair Kits" },
        { value: "campingWaterFilters", label: "Camping Water Filters" },
        { value: "campingWaterPurifiers", label: "Camping Water Purifiers" },
        { value: "waterContainers", label: "Portable Water Containers" },
        { value: "sandbags", label: "Fitness Sandbags" },
        { value: "resistantJackets", label: "Weather-Resistant Jackets" },
        { value: "hydrationPacks", label: "Hydration Packs" },
        { value: "outdoorHats", label: "Outdoor Hats" },
        { value: "backpacks", label: "Backpacks" },
        { value: "trailShoes", label: "Trail Shoes" },
        { value: "compasses", label: "Compasses" },
        { value: "headlamps", label: "Headlamps" },
        { value: "sleepingBags", label: "Sleeping Bags" },
        { value: "campingTents", label: "Camping Tents" },
        { value: "hikingPoles", label: "Hiking Poles" },
        { value: "pocketKnives", label: "Pocket Knives" },
        { value: "gpsDevices", label: "GPS Devices" },
        { value: "binoculars", label: "Binoculars" },
        { value: "portableChargers", label: "Portable Chargers" },
        { value: "multiTools", label: "Multi-Tools" },
        { value: "campingCookware", label: "Camping Cookware" },
        { value: "climbingRopes", label: "Climbing Ropes" },
        { value: "paracord", label: "Paracord" },
        { value: "survivalKits", label: "Survival Kits" },
        { value: "waterproofBags", label: "Waterproof Bags" },
        { value: "outdoorBlankets", label: "Outdoor Blankets" },
        { value: "campingChairs", label: "Camping Chairs" },
        { value: "coolers", label: "Coolers" },
        { value: "sleepingPads", label: "Sleeping Pads" }
      ]
    },
    
    {
      category: "Yoga & Meditation",
      label: "Yoga & Meditation",
      subcategories: [
        { value: "yogaMats", label: "Yoga Mats" },
        { value: "meditationPillows", label: "Meditation Pillows" },
        { value: "yogaBlocks", label: "Yoga Blocks" },
        { value: "yogaStraps", label: "Yoga Straps" },
        { value: "incense", label: "Incense" },
        { value: "zafuCushions", label: "Zafu Cushions" },
        { value: "essentialOils", label: "Essential Oils" },
        { value: "yogaBolsters", label: "Yoga Bolsters" },
        { value: "yogaWheels", label: "Yoga Wheels" },
        { value: "lavenderBags", label: "Lavender Bags" },
        { value: "saltLamps", label: "Himalayan Salt Lamps" },
        { value: "meditationChimes", label: "Meditation Chimes" },
        { value: "chantingBowls", label: "Chanting Bowls" },
        { value: "smudgeSticks", label: "Smudge Sticks" },
        { value: "yogaTowels", label: "Yoga Towels" },
        { value: "yogaPants", label: "Yoga Pants" },
        { value: "sportsBras", label: "Sports Bras" },
        { value: "yogaShirts", label: "Yoga Shirts" },
        { value: "meditationShawls", label: "Meditation Shawls" },
        { value: "socks", label: "Yoga Socks" },
        { value: "headbands", label: "Yoga Headbands" },
        { value: "matBags", label: "Yoga Mat Bags" },
        { value: "yogaGloves", label: "Yoga Gloves" },
        { value: "stretchBands", label: "Stretch Bands" },
        { value: "foamRollers", label: "Foam Rollers" },
        { value: "yogaPillows", label: "Yoga Pillows" },
        { value: "meditationStools", label: "Meditation Stools" },
        { value: "eyePillows", label: "Eye Pillows" },
        { value: "yogaRugs", label: "Yoga Rugs" },
        { value: "yogaBlankets", label: "Yoga Blankets" },
      ]
    },

    {
      category: "Cricket",
      label: "Cricket",
      subcategories: [
        { value: "cricketBats", label: "Cricket Bats" },
        { value: "cricketBalls", label: "Cricket Balls" },
        { value: "cricketPads", label: "Cricket Pads" },
        { value: "cricketGloves", label: "Cricket Gloves" },
        { value: "cricketHelmets", label: "Cricket Helmets" },
        { value: "cricketBags", label: "Cricket Bags" },
        { value: "cricketStumps", label: "Cricket Stumps" },
        { value: "cricketShoes", label: "Cricket Shoes" },
        { value: "cricketJerseys", label: "Cricket Jerseys" },
        { value: "cricketPants", label: "Cricket Pants" },
        { value: "cricketCaps", label: "Cricket Caps" },
        { value: "cricketSocks", label: "Cricket Socks" },
        { value: "cricketArmGuards", label: "Cricket Arm Guards" },
        { value: "cricketThighGuards", label: "Cricket Thigh Guards" },
        { value: "cricketShinGuards", label: "Cricket Shin Guards" },
        { value: "cricketSweaters", label: "Cricket Sweaters" },
        { value: "cricketRainwear", label: "Cricket Rainwear" },
        { value: "cricketWickets", label: "Cricket Wickets" },
        { value: "cricketTrainingAids", label: "Cricket Training Aids" },
        { value: "cricketBowlingMachines", label: "Cricket Bowling Machines" },
        { value: "cricketCages", label: "Cricket Cages" },
        { value: "cricketProtectiveBoxes", label: "Cricket Protective Boxes" },
        { value: "cricketWicketKeepingGloves", label: "Cricket Wicket Keeping Gloves" },
        { value: "cricketWicketKeepingPads", label: "Cricket Wicket Keeping Pads" },
        { value: "cricketMouthguards", label: "Cricket Mouthguards" },
        { value: "cricketShirts", label: "Cricket Shirts" },
        { value: "cricketVests", label: "Cricket Vests" },
        { value: "cricketBelts", label: "Cricket Belts" },
        { value: "cricketBails", label: "Cricket Bails" },
        { value: "cricketBoundaryMarkers", label: "Cricket Boundary Markers" },
        { value: "cricketUmpiresGear", label: "Cricket Umpires Gear" }
      ]
    },

    {
      category: "Squash",
      label: "Squash",
      subcategories: [
        { value: "squashRackets", label: "Squash Rackets" },
        { value: "squashBalls", label: "Squash Balls" },
        { value: "squashShoes", label: "Squash Shoes" },
        { value: "squashGloves", label: "Squash Gloves" },
        { value: "squashBags", label: "Squash Bags" },
        { value: "squashGoggles", label: "Squash Goggles" },
        { value: "squashGrips", label: "Squash Grips" },
        { value: "squashClothing", label: "Squash Clothing" },
        { value: "squashShirts", label: "Squash Shirts" },
        { value: "squashPants", label: "Squash Pants" },
        { value: "squashShorts", label: "Squash Shorts" },
        { value: "squashSocks", label: "Squash Socks" },
        { value: "squashHeadbands", label: "Squash Headbands" },
        { value: "squashArmBands", label: "Squash Arm Bands" },
        { value: "squashSweatbands", label: "Squash Sweatbands" },
        { value: "squashTowels", label: "Squash Towels" },
        { value: "squashKneePads", label: "Squash Knee Pads" },
        { value: "squashWristbands", label: "Squash Wristbands" },
        { value: "squashWarmUpJackets", label: "Squash Warm-Up Jackets" },
        { value: "squashCompressionWear", label: "Squash Compression Wear" },
        { value: "squashTrainingAids", label: "Squash Training Aids" },
        { value: "squashRacketCases", label: "Squash Racket Cases" },
        { value: "squashCourtShoes", label: "Squash Court Shoes" },
        { value: "squashRacketCovers", label: "Squash Racket Covers" },
        { value: "squashGripTapes", label: "Squash Grip Tapes" },
        { value: "squashRacketStrings", label: "Squash Racket Strings" },
        { value: "squashBallContainers", label: "Squash Ball Containers" }
      ]
    },
    
    
    {
      category: "Gymnastics Equipment",
      label: "Gymnastics Equipment",
      subcategories: [
        { value: "gymnasticsMats", label: "Gymnastics Mats" },
        { value: "gymnasticsBars", label: "Gymnastics Bars" },
        { value: "gymnasticsRings", label: "Gymnastics Rings" },
        { value: "gymnasticsBalanceBeams", label: "Gymnastics Balance Beams" },
        { value: "gymnasticsLeotards", label: "Gymnastics Leotards" },
        { value: "gymnasticsGrips", label: "Gymnastics Grips" },
        { value: "gymnasticsFloorMats", label: "Gymnastics Floor Mats" },
        { value: "gymnasticsVault", label: "Gymnastics Vault" },
        { value: "gymnasticsPommelHorses", label: "Gymnastics Pommel Horses" },
        { value: "gymnasticsTrampolines", label: "Gymnastics Trampolines" },
        { value: "gymnasticsParallettes", label: "Gymnastics Parallettes" },
        { value: "gymnasticsPitFoam", label: "Gymnastics Pit Foam" },
        { value: "gymnasticsHandstands", label: "Gymnastics Handstands" },
        { value: "gymnasticsTumbleTrack", label: "Gymnastics Tumble Track" },
        { value: "gymnasticsResistanceBands", label: "Gymnastics Resistance Bands" },
        { value: "gymnasticsStretchingStraps", label: "Gymnastics Stretching Straps" },
        { value: "gymnasticsGymNets", label: "Gymnastics Gym Nets" },
        { value: "gymnasticsGloves", label: "Gymnastics Gloves" },
        { value: "gymnasticsBumperBlocks", label: "Gymnastics Bumper Blocks" },
        { value: "gymnasticsBarPadding", label: "Gymnastics Bar Padding" },
        { value: "gymnasticsBeamPads", label: "Gymnastics Beam Pads" },
        { value: "gymnasticsFoamRollers", label: "Gymnastics Foam Rollers" },
        { value: "gymnasticsKneePads", label: "Gymnastics Knee Pads" },
        { value: "gymnasticsWraps", label: "Gymnastics Wraps" },
        { value: "gymnasticsTights", label: "Tights" },
        { value: "gymnasticsShirts", label: "Shirts" },
        { value: "gymnasticsLeggings", label: "Leggings" },
        { value: "gymnasticsWarmUpJackets", label: " Warm-Up Jackets" },
        { value: "gymnasticsWaterBottles", label: "Water Bottles" }
      ]
    },
    
    {
      category: "Team Sports",
      label: "Soccer/Football/Basketball Equipment",
      subcategories: [
        { value: "soccerBalls", label: "Soccer Balls" },
        { value: "soccerBoots", label: "Soccer Boots" },
        { value: "soccerPads", label: "Soccer Pads" },
        { value: "soccerShinGuards", label: "Soccer Shin Guards" },
        { value: "soccerGoalkeeperGloves", label: "Soccer Goalkeeper Gloves" },
        { value: "soccerJerseys", label: "Soccer Jerseys" },
        { value: "soccerShorts", label: "Soccer Shorts" },
        { value: "soccerSocks", label: "Soccer Socks" },
        { value: "soccerTrainingAids", label: "Soccer Training Aids" },
        { value: "soccerGoalkeeperKits", label: "Soccer Goalkeeper Kits" },
        { value: "soccerBags", label: "Soccer Bags" },
        { value: "soccerRefereeKits", label: "Soccer Referee Kits" },


        { value: "basketballHoops", label: "Basketball Hoops" },
        { value: "basketballBalls", label: "Basketball Balls" },
        { value: "basketballShoes", label: "Basketball Shoes" },
        { value: "basketballJerseys", label: "Basketball Jerseys" },
        { value: "basketballShorts", label: "Basketball Shorts" },
        { value: "basketballSocks", label: "Basketball Socks" },
        { value: "basketballTrainingAids", label: "Basketball Training Aids" },
        { value: "basketballCompressionWear", label: "Basketball Compression Wear" },
        { value: "basketballBackboards", label: "Basketball Backboards" },
        { value: "basketballNets", label: "Basketball Nets" },
        { value: "basketballPumps", label: "Basketball Pumps" },
        { value: "basketballRims", label: "Basketball Rims" },
        { value: "basketballScoreboards", label: "Basketball Scoreboards" },
        { value: "basketballRefereeKits", label: "Basketball Referee Kits" },
        { value: "basketballWhistles", label: "Basketball Whistles" },
        { value: "basketballWaterBottles", label: "Basketball Water Bottles" },
        { value: "basketballTowels", label: "Basketball Towels" },
        { value: "basketballHeadbands", label: "Basketball Headbands" },
        { value: "basketballWristbands", label: "Basketball Wristbands" },
        { value: "basketballAnkleBraces", label: "Basketball Ankle Braces" },
        { value: "basketballKneeBraces", label: "Basketball Knee Braces" },
        { value: "basketballElbowBraces", label: "Basketball Elbow Braces" },
        { value: "basketballMouthguards", label: "Basketball Mouthguards" },
        { value: "basketballGloves", label: "Basketball Gloves" },
        { value: "basketballBags", label: "Basketball Bags" },

        { value: "footballBalls", label: "Football Balls" },
        { value: "footballBoots", label: "Football Boots" },
        { value: "footballHelmets", label: "Football Helmets" },
        { value: "footballJerseys", label: "Football Jerseys" },
        { value: "footballPads", label: "Football Pads" },
        { value: "footballShoulderPads", label: "Football Shoulder Pads" },
        { value: "footballCleats", label: "Football Cleats" },
        { value: "footballMouthguards", label: "Football Mouthguards" },
        { value: "footballGloves", label: "Football Gloves" },
        { value: "footballSocks", label: "Football Socks" },
        { value: "footballCompressionWear", label: "Football Compression Wear" },
        { value: "footballTrainingAids", label: "Football Training Aids" },
        { value: "footballTowels", label: "Football Towels" },
        { value: "footballRefereeKits", label: "Football Referee Kits" }
      ]
    },
    
    {
      category: "Racquet Sports",
      label: "Tennis & Badminton Equipment",
      subcategories: [
        { value: "tennisRackets", label: "Tennis Rackets" },
        { value: "tennisBalls", label: "Tennis Balls" },
        { value: "badmintonRackets", label: "Badminton Rackets" },
        { value: "badmintonBalls", label: "Badminton Balls" },
        { value: "racquetBags", label: "Racquet Bags" },
        { value: "tennisGrips", label: "Tennis Grips" },
        { value: "badmintonShoes", label: "Badminton Shoes" },
        { value: "tennisShoes", label: "Tennis Shoes" },
        { value: "badmintonShirts", label: "Badminton Shirts" },
        { value: "tennisShirts", label: "Tennis Shirts" },
        { value: "badmintonShorts", label: "Badminton Shorts" },
        { value: "tennisShorts", label: "Tennis Shorts" },
        { value: "badmintonSocks", label: "Badminton Socks" },
        { value: "tennisSocks", label: "Tennis Socks" },
        { value: "badmintonCompressionWear", label: "Badminton Compression Wear" },
        { value: "tennisCompressionWear", label: "Tennis Compression Wear" },
        { value: "tennisVisors", label: "Tennis Visors" },
        { value: "badmintonShuttlecocks", label: "Badminton Shuttlecocks" },
        { value: "tennisHeadbands", label: "Tennis Headbands" },
        { value: "badmintonGripTapes", label: "Badminton Grip Tapes" },
        { value: "tennisGripTapes", label: "Tennis Grip Tapes" },
        { value: "tennisStringingKits", label: "Tennis Stringing Kits" },
        { value: "badmintonRacketCovers", label: "Badminton Racket Covers" },
        { value: "tennisRacketCovers", label: "Tennis Racket Covers" },
        { value: "badmintonTrainingAids", label: "Badminton Training Aids" },
        { value: "tennisTrainingAids", label: "Tennis Training Aids" },
        { value: "badmintonWristbands", label: "Badminton Wristbands" },
        { value: "tennisWristbands", label: "Tennis Wristbands" },
        { value: "tennisTowels", label: "Tennis Towels" },
        { value: "badmintonTowels", label: "Badminton Towels" },
        { value: "badmintonRacketStringing", label: "Badminton Racket Stringing" }
      ]
    },
    
    {
      category: "Swimming",
      label: "Swimming & Water Sports",
      subcategories: [
        { value: "swimmingGoggles", label: "Swimming Goggles" },
        { value: "swimmingCaps", label: "Swimming Caps" },
        { value: "swimmingPaddles", label: "Swimming Paddles" },
        { value: "swimmingFins", label: "Swimming Fins" },
        { value: "waterPolo", label: "Water Polo" },
        { value: "swimmingBoards", label: "Swimming Boards" },
        { value: "swimmingSuits", label: "Swimming Suits" },
        { value: "swimmingEarplugs", label: "Swimming Earplugs" },
        { value: "swimmingNoseClips", label: "Swimming Nose Clips" },
        { value: "swimmingSnorkels", label: "Swimming Snorkels" },
        { value: "swimmingKickboards", label: "Swimming Kickboards" },
        { value: "waterAerobicsEquipment", label: "Water Aerobics Equipment" },
        { value: "swimmingResistanceBands", label: "Swimming Resistance Bands" },
        { value: "swimmingTowels", label: "Swimming Towels" },
        { value: "swimmingWaterShoes", label: "Swimming Water Shoes" },
        { value: "swimmingLifeguardWhistles", label: "Swimming Lifeguard Whistles" },
        { value: "swimmingWaterProofBags", label: "Swimming Waterproof Bags" },
        { value: "swimmingHydrationPacks", label: "Swimming Hydration Packs" },
        { value: "swimmingGogglesStraps", label: "Swimming Goggles Straps" },
        { value: "swimmingEarDefenders", label: "Swimming Ear Defenders" },
        { value: "swimmingPerformanceSuits", label: "Swimming Performance Suits" },
        { value: "waterPoloCaps", label: "Water Polo Caps" },
        { value: "waterPoloBalls", label: "Water Polo Balls" },
        { value: "swimmingWetsuits", label: "Swimming Wetsuits" },
        { value: "swimmingMeshBags", label: "Swimming Mesh Bags" },
        { value: "swimmingStretchBands", label: "Swimming Stretch Bands" },
        { value: "swimmingGoggleCases", label: "Swimming Goggle Cases" },
        { value: "wateraerobicsEquipment", label: "Water Aerobics Equipment" },
        { value: "swimmingResistanceBands", label: "Swimming Resistance Bands" }
      ]
    },
    
    {
      category: "cycling",
      label: "Cycling Equipment",
      subcategories: [
        { value: "cyclingBikes", label: "Cycling Bikes" },
        { value: "cyclingHelmets", label: "Cycling Helmets" },
        { value: "cyclingGloves", label: "Cycling Gloves" },
        { value: "cyclingBags", label: "Cycling Bags" },
        { value: "cyclingLights", label: "Cycling Lights" },
        { value: "cyclingShoes", label: "Cycling Shoes" },
        { value: "cyclingJerseys", label: "Cycling Jerseys" },
        { value: "cyclingShorts", label: "Cycling Shorts" },
        { value: "cyclingSocks", label: "Cycling Socks" },
        { value: "cyclingKits", label: "Cycling Kits" },
        { value: "cyclingWaterBottles", label: "Cycling Water Bottles" },
        { value: "cyclingLock", label: "Cycling Lock" },
        { value: "cyclingTubes", label: "Cycling Tubes" },
        { value: "cyclingTires", label: "Cycling Tires" },
        { value: "cyclingPedals", label: "Cycling Pedals" },
        { value: "cyclingChains", label: "Cycling Chains" },
        { value: "cyclingShifters", label: "Cycling Shifters" },
        { value: "cyclingBrakes", label: "Cycling Brakes" },
        { value: "cyclingCages", label: "Cycling Cages" },
        { value: "cyclingRacks", label: "Cycling Racks" },
        { value: "cyclingRepairKits", label: "Cycling Repair Kits" },
        { value: "cyclingPump", label: "Cycling Pump" },
        { value: "cyclingReflectiveVests", label: "Cycling Reflective Vests" },
        { value: "cyclingArmWarmers", label: "Cycling Arm Warmers" },
        { value: "cyclingKneeWarmers", label: "Cycling Knee Warmers" },
        { value: "cyclingShoeCovers", label: "Cycling Shoe Covers" },
        { value: "cyclingRainCapes", label: "Cycling Rain Capes" },
        { value: "cyclingGlasses", label: "Cycling Glasses" },
        { value: "cyclingWindbreakers", label: "Cycling Windbreakers" },
        { value: "cyclingFenders", label: "Cycling Fenders" },
        { value: "cyclingBikeComputers", label: "Cycling Bike Computers" },
        { value: "cyclingHydrationPacks", label: "Cycling Hydration Packs" },
        { value: "cyclingSpareParts", label: "Cycling Spare Parts" },
        { value: "cyclingTrainingAids", label: "Cycling Training Aids" },
        { value: "cyclingSaddleBags", label: "Cycling Saddle Bags" },
        { value: "cyclingTowingSystems", label: "Cycling Towing Systems" }
      ]
    },
    
    {
      category: "Combat Sports",
      label: "Combat Sports Equipment",
      subcategories: [
        { value: "boxingGloves", label: "Boxing Gloves" },
        { value: "boxingBags", label: "Boxing Bags" },
        { value: "mmaGloves", label: "MMA Gloves" },
        { value: "headGuards", label: "Head Guards" },
        { value: "shinGuards", label: "Shin Guards" },
        { value: "mouthGuards", label: "Mouth Guards" },
        { value: "handWraps", label: "Hand Wraps" },
        { value: "punchingPads", label: "Punching Pads" },
        { value: "focusMitt", label: "Focus Mitts" },
        { value: "speedBags", label: "Speed Bags" },
        { value: "punchingBall", label: "Punching Ball" },
        { value: "mmaShorts", label: "MMA Shorts" },
        { value: "boxingShoes", label: "Boxing Shoes" },
        { value: "kickboxingGloves", label: "Kickboxing Gloves" },
        { value: "trainingDummies", label: "Training Dummies" },
        { value: "wrestlingShoes", label: "Wrestling Shoes" },
        { value: "combatSportsApparel", label: "Combat Sports Apparel" },
        { value: "boxingHandWraps", label: "Boxing Hand Wraps" },
        { value: "boxingRobes", label: "Boxing Robes" },
        { value: "boxingTrunks", label: "Boxing Trunks" },
        { value: "mmaRashGuards", label: "MMA Rash Guards" },
        { value: "mmaCompressionShorts", label: "MMA Compression Shorts" },
        { value: "boxingHeadgear", label: "Boxing Headgear" },
        { value: "kickboxingPads", label: "Kickboxing Pads" },
        { value: "fightMouthguards", label: "Fight Mouthguards" },
        { value: "combatSportsTowels", label: "Combat Sports Towels" },
        { value: "mmaKicks", label: "MMA Kicks" },
        { value: "combatSportsBags", label: "Combat Sports Bags" },
        { value: "grapplingGloves", label: "Grappling Gloves" },
        { value: "boxingJumpRopes", label: "Boxing Jump Ropes" },
        { value: "combatSportsProtection", label: "Combat Sports Protection" }
      ]
    },
    
    {
      category: "WinterSports",
      label: "Winter Sports Equipment",
      subcategories: [
        { value: "snowboards", label: "Snowboards" },
        { value: "skiGear", label: "Ski Gear" },
        { value: "skiPoles", label: "Ski Poles" },
        { value: "snowSuits", label: "Snow Suits" },
        { value: "sledges", label: "Sledges" },
        { value: "skiBoots", label: "Ski Boots" },
        { value: "snowGoggles", label: "Snow Goggles" },
        { value: "snowboardBoots", label: "Snowboard Boots" },
        { value: "skiGloves", label: "Ski Gloves" },
        { value: "snowboardGloves", label: "Snowboard Gloves" },
        { value: "winterHelmets", label: "Winter Sports Helmets" },
        { value: "snowboardBindings", label: "Snowboard Bindings" },
        { value: "skiBindings", label: "Ski Bindings" },
        { value: "snowboardJackets", label: "Snowboard Jackets" },
        { value: "skiJackets", label: "Ski Jackets" },
        { value: "winterBoots", label: "Winter Boots" },
        { value: "thermalUnderwear", label: "Thermal Underwear" },
        { value: "snowboardPants", label: "Snowboard Pants" },
        { value: "skiPants", label: "Ski Pants" },
        { value: "snowSocks", label: "Snow Socks" },
        { value: "handWarmers", label: "Hand Warmers" },
        { value: "footWarmers", label: "Foot Warmers" },
        { value: "skiMasks", label: "Ski Masks" },
        { value: "snowboardHelmets", label: "Snowboard Helmets" },
        { value: "snowShovels", label: "Snow Shovels" },
        { value: "avalancheGear", label: "Avalanche Safety Gear" },
        { value: "winterBackpacks", label: "Winter Backpacks" },
        { value: "skiLock", label: "Ski Lock" },
        { value: "skiTuningKits", label: "Ski Tuning Kits" },
        { value: "snowboardWax", label: "Snowboard Wax" },
        { value: "snowboardTuningKits", label: "Snowboard Tuning Kits" },
        { value: "skiTuningTools", label: "Ski Tuning Tools" },
        { value: "skiMasks", label: "Ski Masks" },
        { value: "winterSportsGlasses", label: "Winter Sports Glasses" },
        { value: "iceSkates", label: "Ice Skates" },
        { value: "iceSkatingSuits", label: "Ice Skating Suits" },
        { value: "snowboardBags", label: "Snowboard Bags" },
        { value: "skiBags", label: "Ski Bags" },
        { value: "skiStraps", label: "Ski Straps" }
      ]
    },
    
    {
      category: "Kabaddi",
      label: "Kabaddi Equipment",
      subcategories: [
        { value: "kabaddiBalls", label: "Kabaddi Balls" },
        { value: "kabaddiShoes", label: "Kabaddi Shoes" },
        { value: "kabaddiPads", label: "Kabaddi Pads" },
        { value: "kabaddiJerseys", label: "Kabaddi Jerseys" },
        { value: "kabaddiGloves", label: "Kabaddi Gloves" },
        { value: "kabaddiKneePads", label: "Kabaddi Knee Pads" },
        { value: "kabaddiElbowPads", label: "Kabaddi Elbow Pads" },
        { value: "kabaddiShorts", label: "Kabaddi Shorts" },
        { value: "kabaddiTracksuits", label: "Kabaddi Tracksuits" },
        { value: "kabaddiHeadgear", label: "Kabaddi Headgear" },
        { value: "kabaddiArmGuards", label: "Kabaddi Arm Guards" },
        { value: "kabaddiTrainingVests", label: "Kabaddi Training Vests" },
        { value: "kabaddiBelts", label: "Kabaddi Belts" },
        { value: "kabaddiT-shirts", label: "Kabaddi T-shirts" },
        { value: "kabaddiWaterBottles", label: "Kabaddi Water Bottles" },
        { value: "kabaddiResistanceBands", label: "Kabaddi Resistance Bands" },
        { value: "kabaddiRecoveryTowels", label: "Kabaddi Recovery Towels" },
        { value: "kabaddiFirstAidKits", label: "Kabaddi First Aid Kits" },
        { value: "kabaddiMouthGuards", label: "Kabaddi Mouth Guards" },
        { value: "kabaddiTrainingCones", label: "Kabaddi Training Cones" },
        { value: "kabaddiWhistles", label: "Kabaddi Whistles" },
        { value: "kabaddiRefereeFlags", label: "Kabaddi Referee Flags" },
        { value: "kabaddiSocks", label: "Kabaddi Socks" },
        { value: "kabaddiGoalMarkers", label: "Kabaddi Goal Markers" }
      ]
    },
    
    {
      category: "kids Sports",
      label: "Kids Sports & Equipment",
      subcategories: [
        { value: "babyfoods", label: "Baby Foods" },
        { value: "babyClothing", label: "Baby Clothing" },
        { value: "diapers", label: "Diapers" },
        { value: "wipes", label: "Wipes" },
        { value: "babyskinCare", label: "Baby Skin Care" },
        { value: "kidsBalls", label: "Kids Balls" },
        { value: "kidsShoes", label: "Kids Shoes" },
        { value: "kidsPads", label: "Kids Pads" },
        { value: "kidsHelmets", label: "Kids Helmets" },
        { value: "kidsGloves", label: "Kids Gloves" },
        { value: "kidsJerseys", label: "Kids Jerseys" },
        { value: "kidsRackets", label: "Kids Rackets" },
        { value: "kidsSkates", label: "Kids Skates" },
        { value: "kidsScooters", label: "Kids Scooters" },
        { value: "kidsBicycles", label: "Kids Bicycles" },
        { value: "kidsScooterHelmets", label: "Kids Scooter Helmets" },
        { value: "kidsSportsSocks", label: "Kids Sports Socks" },
        { value: "kidsSwimmingGoggles", label: "Kids Swimming Goggles" },
        { value: "kidsSwimCaps", label: "Kids Swim Caps" },
        { value: "kidsJumpRopes", label: "Kids Jump Ropes" },
        { value: "kidsYogaMats", label: "Kids Yoga Mats" },
        { value: "kidsTrainingCones", label: "Kids Training Cones" },
        { value: "kidsHockeySticks", label: "Kids Hockey Sticks" },
        { value: "kidsFootball", label: "Kids Football" },
        { value: "kidsBaseballBats", label: "Kids Baseball Bats" },
        { value: "kidsBasketballHoops", label: "Kids Basketball Hoops" },
        { value: "kidsBadmintonRackets", label: "Kids Badminton Rackets" },
        { value: "kidsTennisRackets", label: "Kids Tennis Rackets" },
        { value: "kidsArcherySets", label: "Kids Archery Sets" },
        { value: "kidsPaddles", label: "Kids Paddles" },
        { value: "kidsKickBoards", label: "Kids Kickboards" },
        { value: "kidsBowlingSets", label: "Kids Bowling Sets" },
        { value: "kidsFootballCleats", label: "Kids Football Cleats" }
      ]
    },
    
    {
      category: "Fitness Trackers",
      label: "Fitness Trackers",
      subcategories: [
        { value: "fitnessWatches", label: "Fitness Watches" },
        { value: "fitnessBands", label: "Fitness Bands" },
        { value: "heartRateMonitors", label: "Heart Rate Monitors" },
        { value: "gpsTrackers", label: "GPS Trackers" },
        { value: "smartwatches", label: "Smartwatches" },
        { value: "activityTrackers", label: "Activity Trackers" },
        { value: "sleepTrackers", label: "Sleep Trackers" },
        { value: "calorieTrackers", label: "Calorie Trackers" },
        { value: "pedometers", label: "Pedometers" },
        { value: "bloodPressureMonitors", label: "Blood Pressure Monitors" },
        { value: "fitnessApps", label: "Fitness Apps" },
        { value: "bodyCompositionMonitors", label: "Body Composition Monitors" },
        { value: "fitnessSmartScales", label: "Fitness Smart Scales" },
        { value: "spO2Monitors", label: "SpO2 Monitors" },
        { value: "fitnessChestStraps", label: "Fitness Chest Straps" },
        { value: "electrocardiogramMonitors", label: "ECG Monitors" },
        { value: "swimTrackers", label: "Swim Trackers" },
        { value: "multiSportTrackers", label: "Multi-Sport Trackers" },
        { value: "fitnessTrackerBands", label: "Fitness Tracker Bands" },
        { value: "cyclingComputers", label: "Cycling Computers" },
        { value: "activityMonitors", label: "Activity Monitors" },
        { value: "runningTrackers", label: "Running Trackers" }
      ]
    },
    
    {
      category: "Athletic Care",
      label: "Athletic Care & Recovery",
      subcategories: [
        { value: "icePacks", label: "Ice Packs" },
        { value: "muscleCream", label: "Muscle Cream" },
        { value: "tape", label: "Tape" },
        { value: "compressionSleeves", label: "Compression Sleeves" },
        { value: "massageRollers", label: "Massage Rollers" },
        { value: "foamRollers", label: "Foam Rollers" },
        { value: "stretchBands", label: "Stretch Bands" },
        { value: "jointSupportBraces", label: "Joint Support Braces" },
        { value: "kneeBraces", label: "Knee Braces" },
        { value: "ankleBraces", label: "Ankle Braces" },
        { value: "elbowBraces", label: "Elbow Braces" },
        { value: "heatPatches", label: "Heat Patches" },
        { value: "coldCompress", label: "Cold Compress" },
        { value: "iceBaths", label: "Ice Baths" },
        { value: "recoveryBoots", label: "Recovery Boots" },
        { value: "massageGuns", label: "Massage Guns" },
        { value: "therapeuticGel", label: "Therapeutic Gel" },
        { value: "ankleSupport", label: "Ankle Support" },
        { value: "tensTherapyDevices", label: "TENS Therapy Devices" },
        { value: "muscleStimulators", label: "Muscle Stimulators" },
        { value: "recoverySocks", label: "Recovery Socks" },
        { value: "hotWaterBottles", label: "Hot Water Bottles" },
        { value: "mobilityTools", label: "Mobility Tools" },
        { value: "postWorkoutSupplements", label: "Post Workout Supplements" }
      ]
    },
    
    {
      category: "Sports Nutrition",
      label: "Sports Nutrition",
      subcategories: [
        { value: "proteinPowder", label: "Protein Powder" },
        { value: "energyBars", label: "Energy Bars" },
        { value: "electrolyteDrinks", label: "Electrolyte Drinks" },
        { value: "preWorkout", label: "Pre-Workout" },
        { value: "postWorkout", label: "Post-Workout" },
        { value: "shilajit", label: "Shilajit" },
        { value: "aminoAcids", label: "Amino Acids" },
        { value: "creatine", label: "Creatine" },
        { value: "branchChainAminoAcids", label: "BCAA (Branch Chain Amino Acids)" },
        { value: "weightGain", label: "Weight Gain Supplements" },
        { value: "fatBurners", label: "Fat Burners" },
        { value: "mealReplacement", label: "Meal Replacement" },
        { value: "collagen", label: "Collagen Supplements" },
        { value: "vitamins", label: "Vitamins & Minerals" },
        { value: "fishOil", label: "Fish Oil" },
        { value: "greensPowder", label: "Greens Powder" },
        { value: "probiotics", label: "Probiotics" },
        { value: "caffeineSupplements", label: "Caffeine Supplements" },
        { value: "hydrolyzedProtein", label: "Hydrolyzed Protein" },
        { value: "carbPowder", label: "Carb Powder" },
        { value: "hydrationPowders", label: "Hydration Powders" },
        { value: "glutamine", label: "Glutamine" },
        { value: "jointSupplements", label: "Joint Supplements" },
        { value: "detoxTeas", label: "Detox Teas" },
        { value: "snackProtein", label: "Protein Snacks" }
      ]
    },
    
    {
      category: "Dry Fruits",
      label: "Dry Fruits",
      subcategories: [
        { value: "almonds", label: "Almonds" },
        { value: "cashews", label: "Cashews" },
        { value: "pistachios", label: "Pistachios" },
        { value: "walnuts", label: "Walnuts" },
        { value: "raisins", label: "Raisins" },
        { value: "apricots", label: "Dried Apricots" },
        { value: "dates", label: "Dates" },
        { value: "figs", label: "Dried Figs" },
        { value: "prunes", label: "Prunes" },
        { value: "sultanas", label: "Sultanas" },
        { value: "driedMango", label: "Dried Mango" },
        { value: "driedPapaya", label: "Dried Papaya" },
        { value: "cranberries", label: "Dried Cranberries" },
        { value: "gojiBerries", label: "Goji Berries" },
        { value: "blueberries", label: "Dried Blueberries" },
        { value: "cherries", label: "Dried Cherries" },
        { value: "hazelnuts", label: "Hazelnuts" },
        { value: "pecans", label: "Pecans" },
        { value: "brazilNuts", label: "Brazil Nuts" },
        { value: "macadamiaNuts", label: "Macadamia Nuts" },
        { value: "pineNuts", label: "Pine Nuts" },
        { value: "sunflowerSeeds", label: "Sunflower Seeds" },
        { value: "pumpkinSeeds", label: "Pumpkin Seeds" },
        { value: "chiaSeeds", label: "Chia Seeds" },
        { value: "flaxSeeds", label: "Flax Seeds" }
      ]
    },
    
    {
      category: "Cooking Essentials",
      label: "Cooking Essentials",
      subcategories: [
        { value: "spices", label: "Spices" },
        { value: "oils", label: "Oils" },
        { value: "sauces", label: "Sauces" },
        { value: "herbs", label: "Herbs" },
        { value: "seasonings", label: "Seasonings" },
        { value: "vinegars", label: "Vinegars" },
        { value: "salts", label: "Salts" },
        { value: "sweeteners", label: "Sweeteners" },
        { value: "mustard", label: "Mustard" },
        { value: "ketchup", label: "Ketchup" },
        { value: "mayonnaise", label: "Mayonnaise" },
        { value: "barbecueSauces", label: "Barbecue Sauces" },
        { value: "hotSauces", label: "Hot Sauces" },
        { value: "soySauces", label: "Soy Sauces" },
        { value: "fishSauces", label: "Fish Sauces" },
        { value: "cookingWine", label: "Cooking Wine" },
        { value: "coconutMilk", label: "Coconut Milk" },
        { value: "tomatoPaste", label: "Tomato Paste" },
        { value: "peanutButter", label: "Peanut Butter" },
        { value: "almondButter", label: "Almond Butter" },
        { value: "coconutOil", label: "Coconut Oil" },
        { value: "oliveOil", label: "Olive Oil" },
        { value: "sesameOil", label: "Sesame Oil" },
        { value: "avocadoOil", label: "Avocado Oil" },
        { value: "canolaOil", label: "Canola Oil" },
        { value: "truffleOil", label: "Truffle Oil" },
        { value: "gravy", label: "Gravy" },
        { value: "cheeseSauces", label: "Cheese Sauces" },
        { value: "spreads", label: "Spreads" },
        { value: "chutneys", label: "Chutneys" },
        { value: "pickles", label: "Pickles" },
        { value: "saladDressings", label: "Salad Dressings" },
        { value: "balsamicVinegar", label: "Balsamic Vinegar" },
        { value: "appleCiderVinegar", label: "Apple Cider Vinegar" }
      ]
    },
    
    {
      category: "Training Equipment",
      label: "Training Equipment",
      subcategories: [
        { value: "trainingDummies", label: "Training Dummies" },
        { value: "sleds", label: "Sleds" },
        { value: "agilityLadders", label: "Agility Ladders" },
        { value: "trainingCones", label: "Training Cones" },
        { value: "speedChutes", label: "Speed Chutes" },
        { value: "resistanceBands", label: "Resistance Bands" },
        { value: "balanceBoards", label: "Balance Boards" },
        { value: "hurdles", label: "Hurdles" },
        { value: "medicineBalls", label: "Medicine Balls" },
        { value: "kettlebells", label: "Kettlebells" },
        { value: "battleRopes", label: "Battle Ropes" },
        { value: "jumpRopes", label: "Jump Ropes" },
        { value: "punchingBags", label: "Punching Bags" },
        { value: "speedBalls", label: "Speed Balls" },
        { value: "plyometricBoxes", label: "Plyometric Boxes" },
        { value: "sledPushers", label: "Sled Pushers" },
        { value: "weightedVests", label: "Weighted Vests" },
        { value: "reactionBalls", label: "Reaction Balls" },
        { value: "resistanceParachutes", label: "Resistance Parachutes" },
        { value: "speedHurdles", label: "Speed Hurdles" },
        { value: "verticalJumpTrainer", label: "Vertical Jump Trainer" },
        { value: "trainingBells", label: "Training Bells" },
        { value: "pushUpBars", label: "Push-Up Bars" },
        { value: "focusPads", label: "Focus Pads" }
      ]
    },
    
    {
      category: "Sports Accessories",
      label: "Sports Accessories",
      subcategories: [
        { value: "sportsBags", label: "Sports Bags" },
        { value: "sportsWaterBottles", label: "Sports Water Bottles" },
        { value: "sportsWear", label: "Sports Wear" },
        { value: "sportsTowels", label: "Sports Towels" },
        { value: "sportsCaps", label: "Sports Caps" },
        { value: "sportsSocks", label: "Sports Socks" },
        { value: "sportsHeadbands", label: "Sports Headbands" },
        { value: "sportsWristbands", label: "Sports Wristbands" },
        { value: "sportsShirts", label: "Sports Shirts" },
        { value: "sportsShorts", label: "Sports Shorts" },
        { value: "sportsShoes", label: "Sports Shoes" },
        { value: "compressionGear", label: "Compression Gear" },
        { value: "sportsGloves", label: "Sports Gloves" },
        { value: "armBands", label: "Arm Bands" },
        { value: "sportsBelts", label: "Sports Belts" },
        { value: "sportsHats", label: "Sports Hats" },
        { value: "sportsGoggles", label: "Sports Goggles" },
        { value: "sportsProtection", label: "Sports Protection" },
        { value: "gymTowels", label: "Gym Towels" },
        { value: "sportsShoelaces", label: "Sports Shoelaces" },
        { value: "sportsPads", label: "Sports Pads" },
        { value: "sportsTapes", label: "Sports Tapes" },
        { value: "fitnessBands", label: "Fitness Bands" }
      ]
    },
  ];
